# Generated by Django 5.2.10 on 2026-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da operação', verbose_name='Data')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('SAQUE', 'Saque')], help_text='Compra ou Saque', max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor em reais', max_digits=12, verbose_name='Valor (R$)')),
                ('lugar', models.CharField(help_text='Ex: CLEAR, INTER', max_length=50, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'ordering': ['-data'],
            },
        ),
    ]
