# Generated by Django 5.2.10 on 2026-01-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do índice', verbose_name='Data')),
                ('nome', models.CharField(help_text='Ex: BTC, IFIX, S&P500, Bovespa, Inflação', max_length=100, verbose_name='Nome do Índice')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor do índice', max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Índice',
                'verbose_name_plural': 'Índices',
                'ordering': ['-data', 'nome'],
                'unique_together': {('data', 'nome')},
            },
        ),
    ]
