# Generated by Django 5.2.10 on 2026-01-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aporte',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição ou observações sobre o aporte', null=True, verbose_name='Descrição'),
        ),
    ]
