# Generated by Django 5.2.10 on 2026-01-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_aporte_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da posição', verbose_name='Data')),
                ('classe_ativo', models.CharField(choices=[('SALDO', 'Saldo'), ('RESERVA', 'Reserva de Emergência'), ('ETF', "ETF's"), ('FII', 'FII'), ('CRIPTO', 'Criptos'), ('ACAO', 'Ações')], help_text='Categoria do ativo', max_length=20, verbose_name='Classe de Ativo')),
                ('ativo', models.CharField(help_text='Ex: TESOURO, CDB, LCA, BOVA11, BTC, ETH, BBAS3', max_length=100, verbose_name='Ativo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Quanto você tem em reais neste ativo', max_digits=15, verbose_name='Valor (R$)')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'ordering': ['-data', 'classe_ativo', 'ativo'],
                'unique_together': {('data', 'classe_ativo', 'ativo')},
            },
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
    ]
