# Generated by Django 5.2.10 on 2026-01-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_posicao_delete_cotacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ex: Reserva, Cripto, S&P500, Ações, FII', max_length=100, unique=True, verbose_name='Tipo de Ativo')),
                ('meta', models.DecimalField(decimal_places=2, help_text='Percentual meta para este tipo de ativo', max_digits=5, verbose_name='Meta (%)')),
            ],
            options={
                'verbose_name': 'Meta de Portfólio',
                'verbose_name_plural': 'Metas de Portfólio',
                'ordering': ['tipo'],
            },
        ),
    ]
