# Generated by Django 5.2.10 on 2026-01-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_meta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='MetaPortfolio',
        ),
    ]
