# Generated by Django 4.2.29 on 2026-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_rename_meta_metaportfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data do dividendo recebido', verbose_name='Data')),
                ('ativo', models.CharField(help_text='Ex: BBAS3, BOVA11, ITUB4', max_length=100, verbose_name='Ativo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do dividendo', max_digits=12, verbose_name='Valor (R$)')),
                ('tipo', models.CharField(blank=True, help_text='Ex: Dividendo, JCP, Aluguel', max_length=50, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Dividendo',
                'verbose_name_plural': 'Dividendos',
                'ordering': ['-data'],
            },
        ),
    ]
