# Generated by Django 4.2.29 on 2026-04-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_dividendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: BBAS3, BOVA11, BTC, CDB, TESOURO', max_length=100, unique=True, verbose_name='Nome/Código')),
                ('classe_ativo', models.CharField(choices=[('SALDO', 'Saldo'), ('RESERVA', 'Reserva de Emergência'), ('ETF', "ETF's"), ('FII', 'FII'), ('CRIPTO', 'Criptos'), ('ACAO', 'Ações')], help_text='Categoria do ativo', max_length=20, verbose_name='Classe de Ativo')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['classe_ativo', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='posicao',
            options={'ordering': ['-data', 'ativo'], 'verbose_name': 'Posição', 'verbose_name_plural': 'Posições'},
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dividendo',
            name='ativo',
            field=models.ForeignKey(help_text='Ativo que gerou o dividendo', on_delete=django.db.models.deletion.PROTECT, to='investments.ativo'),
        ),
        migrations.AlterField(
            model_name='posicao',
            name='ativo',
            field=models.ForeignKey(help_text='Ativo referenciado', on_delete=django.db.models.deletion.PROTECT, to='investments.ativo'),
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('data', 'ativo')},
        ),
        migrations.RemoveField(
            model_name='posicao',
            name='classe_ativo',
        ),
    ]
