# Generated by Django 5.2.13 on 2026-08-25 14:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_normalize_inflacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='preco_medio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço médio de compra por unidade, calculado automaticamente a partir das compras', max_digits=15, null=True, verbose_name='Preço Médio (R$)'),
        ),
        migrations.AddField(
            model_name='ativo',
            name='quantidade',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Quantidade de cotas/ações atualmente em carteira', max_digits=18, verbose_name='Quantidade'),
        ),
    ]
