# Generated by Django 5.2.13 on 2026-08-26 12:49

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_normalize_inflacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicao',
            old_name='valor',
            new_name='valor_atual',
        ),
        migrations.AddField(
            model_name='posicao',
            name='preco_medio_compra',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Preço médio de aquisição do ativo', max_digits=15, verbose_name='Preço Médio (R$)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicao',
            name='quantidade',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Quantidade de unidades do ativo', max_digits=15, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicao',
            name='resultado_total',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quantidade'), '*', django.db.models.expressions.CombinedExpression(models.F('valor_atual'), '-', models.F('preco_medio_compra'))), help_text='Ganho/perda de capital: quantidade × (valor atual - preço médio de compra)', output_field=models.DecimalField(decimal_places=2, max_digits=18), verbose_name='Resultado (R$)'),
        ),
    ]
