# Generated by Django 5.2.13 on 2026-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_rename_valor_posicao_valor_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='tipo_movimento',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('ATUALIZACAO', 'Atualização')], default='ATUALIZACAO', help_text='Última ação registrada para este ativo nesta data', max_length=20, verbose_name='Ação'),
        ),
    ]
