# Generated by Django 5.2.13 on 2026-08-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_ativo_preco_medio_ativo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='preco_medio',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço médio do ativo logo após esta movimentação', max_digits=15, null=True, verbose_name='Preço médio do ativo (R$)'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='preco_unitario',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preço por unidade desta movimentação (valor / quantidade)', max_digits=15, null=True, verbose_name='Preço por unidade (R$)'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Quantidade comprada/vendida nesta movimentação, quando aplicável', max_digits=18, null=True, verbose_name='Quantidade movimentada'),
        ),
    ]
