# Generated by Django 5.2.13 on 2026-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_posicao_preco_medio_posicao_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('ATUALIZACAO', 'Atualização')], help_text='Se esta posição veio de uma compra, venda ou atualização de valor', max_length=20, null=True, verbose_name='Tipo de movimentação'),
        ),
    ]
