# Generated by Django 5.2.13 on 2026-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_fix_resultado_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividendo',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantidade de cotas/ações na época do pagamento (usada para calcular o valor por cota)', max_digits=15, null=True, verbose_name='Quantidade'),
        ),
    ]
